export type ApplianceCategory =
  | "kitchen"
  | "climate"
  | "laundry"
  | "electronics"
  | "transport"
  | "personal";

export type ApplianceConfig = {
  slug: string;
  displayName: string;
  category: ApplianceCategory;
  wattageRange: {
    min: number;
    max: number;
  };
  averageWattage: number;
  typicalUsageHoursPerDay: number;
  introFragment: string;
  usageNote: string;
  variabilityFactors: string[];
};

export const APPLIANCE_CONFIGS = [
  {
    slug: "refrigerator",
    displayName: "Refrigerator",
    category: "kitchen",
    wattageRange: { min: 100, max: 250 },
    averageWattage: 180,
    typicalUsageHoursPerDay: 8,
    introFragment: "a typical compressor-cycle refrigerator",
    usageNote: "Refrigerators cycle on and off during the day, so the average running load is lower than peak startup wattage.",
    variabilityFactors: ["appliance age", "door-opening frequency", "garage vs indoor placement"],
  },
  {
    slug: "space-heater",
    displayName: "Space Heater",
    category: "climate",
    wattageRange: { min: 750, max: 1500 },
    averageWattage: 1500,
    typicalUsageHoursPerDay: 4,
    introFragment: "a plug-in electric resistance space heater",
    usageNote: "Most space heaters draw close to their rated wattage when actively heating, which makes them one of the more expensive household appliances to run.",
    variabilityFactors: ["thermostat cycling", "room insulation", "outdoor temperature"],
  },
  {
    slug: "window-ac",
    displayName: "Window AC",
    category: "climate",
    wattageRange: { min: 500, max: 1500 },
    averageWattage: 900,
    typicalUsageHoursPerDay: 8,
    introFragment: "a standard window air conditioner",
    usageNote: "Window AC units cycle based on thermostat demand, so real-world daily cost depends heavily on weather and setpoint.",
    variabilityFactors: ["BTU size", "climate", "thermostat setting"],
  },
  {
    slug: "portable-ac",
    displayName: "Portable AC",
    category: "climate",
    wattageRange: { min: 700, max: 1400 },
    averageWattage: 1100,
    typicalUsageHoursPerDay: 6,
    introFragment: "a portable air conditioner",
    usageNote: "Portable AC units often consume more electricity per room cooled than window units, especially in hotter climates.",
    variabilityFactors: ["hose configuration", "room size", "daily runtime"],
  },
  {
    slug: "central-ac",
    displayName: "Central AC",
    category: "climate",
    wattageRange: { min: 2000, max: 5000 },
    averageWattage: 3500,
    typicalUsageHoursPerDay: 8,
    introFragment: "a central air conditioning system",
    usageNote: "Central AC cost depends on home size, system efficiency, and climate, but the statewide electricity rate still strongly affects total operating cost.",
    variabilityFactors: ["home square footage", "SEER rating", "humidity and summer temperatures"],
  },
  {
    slug: "clothes-dryer",
    displayName: "Clothes Dryer",
    category: "laundry",
    wattageRange: { min: 1800, max: 5000 },
    averageWattage: 3000,
    typicalUsageHoursPerDay: 0.75,
    introFragment: "an electric clothes dryer",
    usageNote: "Dryers use high wattage for shorter periods, so cost depends more on frequency of loads than continuous runtime.",
    variabilityFactors: ["load size", "moisture sensor efficiency", "vent cleanliness"],
  },
  {
    slug: "washing-machine",
    displayName: "Washing Machine",
    category: "laundry",
    wattageRange: { min: 400, max: 1400 },
    averageWattage: 700,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "a typical household washing machine",
    usageNote: "Washing machines generally use less electricity than dryers, but hot-water wash cycles can raise total energy cost indirectly.",
    variabilityFactors: ["wash temperature", "load frequency", "machine efficiency"],
  },
  {
    slug: "dishwasher",
    displayName: "Dishwasher",
    category: "kitchen",
    wattageRange: { min: 1200, max: 1800 },
    averageWattage: 1500,
    typicalUsageHoursPerDay: 1,
    introFragment: "a standard dishwasher",
    usageNote: "Dishwasher energy use depends on cycle length and whether the unit heats water internally.",
    variabilityFactors: ["heated dry setting", "eco mode", "number of cycles per week"],
  },
  {
    slug: "electric-oven",
    displayName: "Electric Oven",
    category: "kitchen",
    wattageRange: { min: 2000, max: 5000 },
    averageWattage: 3000,
    typicalUsageHoursPerDay: 1,
    introFragment: "an electric oven",
    usageNote: "Electric ovens use high wattage while preheating and then cycle to maintain temperature, so cooking time changes the final cost materially.",
    variabilityFactors: ["preheat duration", "temperature setting", "self-clean cycle usage"],
  },
  {
    slug: "microwave",
    displayName: "Microwave",
    category: "kitchen",
    wattageRange: { min: 600, max: 1500 },
    averageWattage: 1200,
    typicalUsageHoursPerDay: 0.25,
    introFragment: "a household microwave",
    usageNote: "Microwaves draw meaningful power when running, but short cooking times keep total monthly cost relatively low.",
    variabilityFactors: ["daily use frequency", "power setting", "meal prep habits"],
  },
  {
    slug: "gaming-pc",
    displayName: "Gaming PC",
    category: "electronics",
    wattageRange: { min: 300, max: 700 },
    averageWattage: 450,
    typicalUsageHoursPerDay: 4,
    introFragment: "a gaming desktop PC",
    usageNote: "Gaming PC electricity use varies widely with GPU load, monitor setup, and idle time versus active gameplay.",
    variabilityFactors: ["graphics card load", "monitor count", "idle vs gaming time"],
  },
  {
    slug: "electric-vehicle-charger",
    displayName: "Electric Vehicle Charger",
    category: "transport",
    wattageRange: { min: 1400, max: 7600 },
    averageWattage: 7200,
    typicalUsageHoursPerDay: 2,
    introFragment: "a Level 2 home EV charger",
    usageNote: "EV charging cost depends on vehicle efficiency and miles driven, but the underlying electricity rate remains the main lever for charging cost by state.",
    variabilityFactors: ["charger level", "miles driven", "charging schedule"],
  },
  {
    slug: "air-purifier",
    displayName: "Air Purifier",
    category: "climate",
    wattageRange: { min: 25, max: 100 },
    averageWattage: 50,
    typicalUsageHoursPerDay: 8,
    introFragment: "a typical HEPA air purifier",
    usageNote: "Air purifiers run continuously when in use, so daily cost scales with hours of operation. Many models have multiple fan speeds that affect power draw.",
    variabilityFactors: ["fan speed setting", "room size", "filter condition"],
  },
  {
    slug: "dehumidifier",
    displayName: "Dehumidifier",
    category: "climate",
    wattageRange: { min: 300, max: 700 },
    averageWattage: 500,
    typicalUsageHoursPerDay: 6,
    introFragment: "a standard residential dehumidifier",
    usageNote: "Dehumidifiers cycle based on humidity levels, so actual runtime varies by season and climate. Basement and crawl-space units often run longer.",
    variabilityFactors: ["humidity setpoint", "room size", "ambient humidity"],
  },
  {
    slug: "ceiling-fan",
    displayName: "Ceiling Fan",
    category: "climate",
    wattageRange: { min: 50, max: 100 },
    averageWattage: 75,
    typicalUsageHoursPerDay: 12,
    introFragment: "a typical ceiling fan",
    usageNote: "Ceiling fans use relatively low wattage but often run for many hours in summer. Cost is low compared to AC but adds up over cooling season.",
    variabilityFactors: ["fan speed", "blade size", "summer vs winter use"],
  },
  {
    slug: "box-fan",
    displayName: "Box Fan",
    category: "climate",
    wattageRange: { min: 60, max: 150 },
    averageWattage: 100,
    typicalUsageHoursPerDay: 8,
    introFragment: "a standard box fan",
    usageNote: "Box fans draw modest power and are often used for room ventilation or supplementing AC. Runtime varies by season.",
    variabilityFactors: ["fan speed", "room ventilation needs", "seasonal use"],
  },
  {
    slug: "laptop",
    displayName: "Laptop",
    category: "electronics",
    wattageRange: { min: 30, max: 120 },
    averageWattage: 65,
    typicalUsageHoursPerDay: 6,
    introFragment: "a typical laptop computer",
    usageNote: "Laptops use far less power than desktops. Charging cycles and screen brightness affect actual draw; many users leave them plugged in continuously.",
    variabilityFactors: ["screen brightness", "charging vs battery mode", "workload intensity"],
  },
  {
    slug: "television",
    displayName: "Television",
    category: "electronics",
    wattageRange: { min: 50, max: 400 },
    averageWattage: 150,
    typicalUsageHoursPerDay: 5,
    introFragment: "a typical LED/LCD television",
    usageNote: "TV power use depends on screen size and brightness. Modern LED sets use less than older LCD or plasma models. Standby draw adds a small constant load.",
    variabilityFactors: ["screen size", "brightness setting", "streaming vs cable"],
  },
  {
    slug: "toaster-oven",
    displayName: "Toaster Oven",
    category: "kitchen",
    wattageRange: { min: 1200, max: 1800 },
    averageWattage: 1500,
    typicalUsageHoursPerDay: 0.25,
    introFragment: "a standard toaster oven",
    usageNote: "Toaster ovens use high wattage during use but typically run for short periods. More efficient than full-size ovens for small meals.",
    variabilityFactors: ["preheat time", "temperature setting", "daily use frequency"],
  },
  {
    slug: "electric-kettle",
    displayName: "Electric Kettle",
    category: "kitchen",
    wattageRange: { min: 1200, max: 1800 },
    averageWattage: 1500,
    typicalUsageHoursPerDay: 0.25,
    introFragment: "an electric kettle",
    usageNote: "Electric kettles draw high power but run for only a few minutes per use. Very efficient for boiling water compared to stovetop.",
    variabilityFactors: ["boil frequency", "water volume", "keep-warm feature"],
  },
  {
    slug: "coffee-maker",
    displayName: "Coffee Maker",
    category: "kitchen",
    wattageRange: { min: 600, max: 1500 },
    averageWattage: 1000,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "a drip coffee maker",
    usageNote: "Coffee makers use most power during the brew cycle. Models with warming plates add continuous draw; programmable units may have standby consumption.",
    variabilityFactors: ["warming plate use", "brew frequency", "carafe size"],
  },
  {
    slug: "hair-dryer",
    displayName: "Hair Dryer",
    category: "personal",
    wattageRange: { min: 1200, max: 2200 },
    averageWattage: 1800,
    typicalUsageHoursPerDay: 0.25,
    introFragment: "a typical hair dryer",
    usageNote: "Hair dryers use high wattage for short periods. Cost depends on daily use frequency and heat setting.",
    variabilityFactors: ["heat setting", "daily use frequency", "hair length and thickness"],
  },
  {
    slug: "freezer",
    displayName: "Freezer",
    category: "kitchen",
    wattageRange: { min: 100, max: 300 },
    averageWattage: 200,
    typicalUsageHoursPerDay: 8,
    introFragment: "a standalone chest or upright freezer",
    usageNote: "Freezers cycle a compressor similarly to refrigerators. Actual draw depends on ambient temperature, door-opening frequency, and whether the unit is in a garage or conditioned space.",
    variabilityFactors: ["chest vs upright design", "ambient temperature", "defrost type"],
  },
  {
    slug: "instant-pot",
    displayName: "Instant Pot",
    category: "kitchen",
    wattageRange: { min: 700, max: 1100 },
    averageWattage: 1000,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "an electric pressure cooker (Instant Pot)",
    usageNote: "Electric pressure cookers draw high wattage during the pressurization phase, then cycle at lower power to maintain temperature. Total cook time is usually short.",
    variabilityFactors: ["cook program selected", "batch size", "pressurization time"],
  },
  {
    slug: "air-fryer",
    displayName: "Air Fryer",
    category: "kitchen",
    wattageRange: { min: 800, max: 1800 },
    averageWattage: 1500,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "a countertop air fryer",
    usageNote: "Air fryers use a heating element and fan to circulate hot air. They draw significant power but typically run for short cooking sessions, keeping total energy use moderate.",
    variabilityFactors: ["basket size", "temperature setting", "daily cooking frequency"],
  },
  {
    slug: "heat-pump",
    displayName: "Heat Pump",
    category: "climate",
    wattageRange: { min: 1000, max: 5000 },
    averageWattage: 3000,
    typicalUsageHoursPerDay: 8,
    introFragment: "a whole-house heat pump system",
    usageNote: "Heat pumps move heat rather than generating it, making them more efficient than resistance heating. Actual consumption varies widely with climate, home size, and system SEER/HSPF rating.",
    variabilityFactors: ["SEER/HSPF rating", "climate zone", "home square footage"],
  },
  {
    slug: "electric-blanket",
    displayName: "Electric Blanket",
    category: "personal",
    wattageRange: { min: 100, max: 200 },
    averageWattage: 150,
    typicalUsageHoursPerDay: 8,
    introFragment: "an electric heated blanket",
    usageNote: "Electric blankets draw modest wattage and are typically used overnight during colder months. Many models have auto-shutoff timers and adjustable heat settings.",
    variabilityFactors: ["heat setting", "blanket size", "auto-shutoff timer"],
  },
  {
    slug: "pool-pump",
    displayName: "Pool Pump",
    category: "climate",
    wattageRange: { min: 500, max: 2500 },
    averageWattage: 1500,
    typicalUsageHoursPerDay: 8,
    introFragment: "a residential swimming pool pump",
    usageNote: "Pool pumps are among the highest-consumption household appliances because they run for many hours daily during the swimming season. Variable-speed pumps can significantly reduce cost.",
    variabilityFactors: ["single-speed vs variable-speed", "pool volume", "daily runtime hours"],
  },
  {
    slug: "hot-tub",
    displayName: "Hot Tub",
    category: "personal",
    wattageRange: { min: 1500, max: 6000 },
    averageWattage: 3500,
    typicalUsageHoursPerDay: 4,
    introFragment: "a residential hot tub or spa",
    usageNote: "Hot tubs use a heater and circulation pump that cycle to maintain water temperature. Keeping the tub heated continuously costs more than heating on demand, especially in cold climates.",
    variabilityFactors: ["insulation quality", "cover use", "ambient temperature"],
  },
  {
    slug: "iron",
    displayName: "Iron",
    category: "personal",
    wattageRange: { min: 800, max: 1500 },
    averageWattage: 1200,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "a household clothes iron",
    usageNote: "Irons draw high wattage while heating but cycle their element to maintain temperature. Total cost depends on how often and how long you iron.",
    variabilityFactors: ["steam vs dry setting", "ironing frequency", "session length"],
  },
  {
    slug: "vacuum-cleaner",
    displayName: "Vacuum Cleaner",
    category: "personal",
    wattageRange: { min: 500, max: 1500 },
    averageWattage: 1000,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "a corded upright or canister vacuum cleaner",
    usageNote: "Vacuum cleaners draw moderate to high wattage but are used for short sessions. Corded models use more power than cordless battery-powered units.",
    variabilityFactors: ["motor power", "cleaning frequency", "floor type"],
  },
  {
    slug: "desktop-computer",
    displayName: "Desktop Computer",
    category: "electronics",
    wattageRange: { min: 150, max: 400 },
    averageWattage: 250,
    typicalUsageHoursPerDay: 6,
    introFragment: "a standard desktop computer for home or office use",
    usageNote: "Desktop computers draw more power than laptops but less than gaming PCs. Actual consumption depends on workload, monitor configuration, and whether peripherals are included.",
    variabilityFactors: ["CPU/GPU workload", "monitor count", "sleep vs active time"],
  },
  {
    slug: "electric-stove-top",
    displayName: "Electric Stove Top",
    category: "kitchen",
    wattageRange: { min: 1200, max: 3000 },
    averageWattage: 2000,
    typicalUsageHoursPerDay: 1,
    introFragment: "an electric cooktop or stove burner",
    usageNote: "Electric stove tops use high wattage per burner but typically run for shorter periods than ovens. Induction models are more efficient than traditional coil or radiant elements.",
    variabilityFactors: ["number of burners used", "induction vs coil", "cooking duration"],
  },
  {
    slug: "garage-door-opener",
    displayName: "Garage Door Opener",
    category: "electronics",
    wattageRange: { min: 300, max: 700 },
    averageWattage: 500,
    typicalUsageHoursPerDay: 0.1,
    introFragment: "a residential garage door opener",
    usageNote: "Garage door openers draw moderate power for very short durations per cycle. Standby power draw is typically 4–7 watts continuously, which adds a small baseline load.",
    variabilityFactors: ["cycles per day", "belt vs chain drive", "standby power draw"],
  },
  {
    slug: "water-heater",
    displayName: "Electric Water Heater",
    category: "climate",
    wattageRange: { min: 3000, max: 5500 },
    averageWattage: 4500,
    typicalUsageHoursPerDay: 2.5,
    introFragment: "a standard electric resistance storage water heater",
    usageNote: "Electric resistance water heaters cycle to maintain tank temperature and recover hot-water usage. Household size and hot-water demand drive most cost variability.",
    variabilityFactors: ["tank size", "household occupancy", "inlet water temperature"],
  },
  {
    slug: "sump-pump",
    displayName: "Sump Pump",
    category: "climate",
    wattageRange: { min: 400, max: 1200 },
    averageWattage: 800,
    typicalUsageHoursPerDay: 1,
    introFragment: "a residential basement sump pump",
    usageNote: "Sump pumps are intermittent-load appliances. Runtime can be low in dry periods and much higher during storms or spring groundwater surges.",
    variabilityFactors: ["rainfall and groundwater levels", "pump horsepower", "drainage cycle frequency"],
  },
  {
    slug: "electric-furnace",
    displayName: "Electric Furnace",
    category: "climate",
    wattageRange: { min: 10000, max: 20000 },
    averageWattage: 15000,
    typicalUsageHoursPerDay: 4,
    introFragment: "a whole-home electric resistance furnace",
    usageNote: "Electric furnaces are high-load heating systems and can materially increase winter electricity costs. Actual runtime varies with insulation quality, thermostat settings, and outdoor temperatures.",
    variabilityFactors: ["home insulation quality", "thermostat setpoint", "winter climate severity"],
  },
  {
    slug: "rice-cooker",
    displayName: "Rice Cooker",
    category: "kitchen",
    wattageRange: { min: 300, max: 1200 },
    averageWattage: 700,
    typicalUsageHoursPerDay: 0.5,
    introFragment: "a countertop electric rice cooker",
    usageNote: "Rice cookers use moderate power during heat-up and low power during keep-warm. Monthly cost depends more on usage frequency than on peak wattage.",
    variabilityFactors: ["cook cycle frequency", "keep-warm duration", "cooker capacity"],
  },
  {
    slug: "humidifier",
    displayName: "Humidifier",
    category: "climate",
    wattageRange: { min: 20, max: 100 },
    averageWattage: 45,
    typicalUsageHoursPerDay: 10,
    introFragment: "a portable room humidifier",
    usageNote: "Humidifiers draw relatively low wattage but often run for long durations in dry seasons. Energy use scales mostly with runtime and mist-output settings.",
    variabilityFactors: ["mist output setting", "room size", "seasonal indoor humidity"],
  },
  {
    slug: "slow-cooker",
    displayName: "Slow Cooker",
    category: "kitchen",
    wattageRange: { min: 150, max: 350 },
    averageWattage: 250,
    typicalUsageHoursPerDay: 4,
    introFragment: "a countertop slow cooker",
    usageNote: "Slow cookers run for longer sessions at lower wattage. Monthly cost remains moderate for most homes and depends primarily on cooking-session hours.",
    variabilityFactors: ["heat setting", "batch size", "session length"],
  },
  {
    slug: "blender",
    displayName: "Blender",
    category: "kitchen",
    wattageRange: { min: 300, max: 1200 },
    averageWattage: 700,
    typicalUsageHoursPerDay: 0.2,
    introFragment: "a household countertop blender",
    usageNote: "Blenders draw moderate-to-high wattage during short blending cycles. Monthly electricity cost is usually driven by usage frequency rather than long runtime.",
    variabilityFactors: ["motor size", "blending duration per use", "daily use frequency"],
  },
  {
    slug: "treadmill",
    displayName: "Treadmill",
    category: "personal",
    wattageRange: { min: 600, max: 1800 },
    averageWattage: 1200,
    typicalUsageHoursPerDay: 0.75,
    introFragment: "a residential electric treadmill",
    usageNote: "Treadmills use meaningful power during workouts, especially at higher speeds and incline settings. Total monthly cost depends primarily on workout duration and frequency.",
    variabilityFactors: ["speed and incline level", "motor efficiency", "workout frequency"],
  },
  {
    slug: "gaming-console",
    displayName: "Gaming Console",
    category: "electronics",
    wattageRange: { min: 70, max: 220 },
    averageWattage: 140,
    typicalUsageHoursPerDay: 2.5,
    introFragment: "a modern home gaming console",
    usageNote: "Gaming consoles use moderate electricity during active play and much less in standby. Monthly cost depends mostly on active gaming hours and power mode settings.",
    variabilityFactors: ["active play time", "graphics intensity", "standby power settings"],
  },
  {
    slug: "wi-fi-router",
    displayName: "Wi-Fi Router",
    category: "electronics",
    wattageRange: { min: 6, max: 20 },
    averageWattage: 12,
    typicalUsageHoursPerDay: 24,
    introFragment: "a household wi-fi router",
    usageNote: "Wi-Fi routers draw low but continuous power. Because they run all day, annual cost is driven by always-on runtime rather than high peak wattage.",
    variabilityFactors: ["router hardware generation", "mesh node count", "power-saving features"],
  },
] as const satisfies readonly ApplianceConfig[];

export type ApplianceSlug = (typeof APPLIANCE_CONFIGS)[number]["slug"];

export const SUPPORTED_APPLIANCE_SLUGS = APPLIANCE_CONFIGS.map((appliance) => appliance.slug) as ApplianceSlug[];

export const FEATURED_APPLIANCE_SLUGS = [
  "refrigerator",
  "space-heater",
  "window-ac",
] as const satisfies readonly ApplianceSlug[];

export function isSupportedApplianceSlug(value: string): value is ApplianceSlug {
  return SUPPORTED_APPLIANCE_SLUGS.includes(value as ApplianceSlug);
}

export function getApplianceConfig(slug: ApplianceSlug): ApplianceConfig {
  const appliance = APPLIANCE_CONFIGS.find((item) => item.slug === slug);
  if (!appliance) {
    throw new Error(`Unsupported appliance slug: ${slug}`);
  }
  return appliance;
}
